### ISSUE TITLE
Changing cleanup time to 0 in chicken chunk config to fix #81 

### ISSUE THREAD

**Issue by quentin452** [The-Magma-Grounds/Projects#5]
https://github.com/embeddedt/ArchaicFix/issues/81
[[**Is your feature request related to a problem? Please describe.**
The problem is, cleanup time in chicken chunk making ghost chunk loading

**Describe the solution you'd like**
Just changing cleanup time to 0 to fix it

**Checklist**
Please read and agree to the following by adding an X into [].

[X] - I agree that I will not get support if I modified the modpack or if I'm using OptiFine.
[X] - I have read and agreed to the GitHub and Discord rules/guidelines.
[] - I have tried asking the mod developer(s) first.

By opening an issue, you agree with our rules/guidelines. If you're some troll who opened this to get attention for no reason, then this issue will be deleted without warning and will result in you being blocked from this repository.

**Comment by MagmaBro123** [comment]
Fixed in 1.3.
